/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package bls */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "exports.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// C_SignSlot
extern int C_SignSlot(char* dataHash, int dataHashLen, char* secpSk, int secpSkLen, char** sig, int* sigLen, char** slotHash, int* slotHashLen);

// C_SignRootHash 导出版本 (Renamed from SignRootHash)
extern int C_SignRootHash(char* rootHash, int rootHashLen, char* blsSk, int blsSkLen, char** sig, int* sigLen);

// C_GenerateCA 导出版本 (Renamed from GenerateCA)
extern int C_GenerateCA(char* publicKey, int publicKeyLen, char* sk, int skLen, int epochLower, int epochUpper, char** caJson, int* caJsonLen);

// C_VerifyCA 导出版本
extern int C_VerifyCA(char* publicKey, int publicKeyLen, char* decryptKey, int decryptKeyLen, int epochLower, int epochUpper, char* signature, int signatureLen);

// C_GenerateSecp256K1Key 导出版本 (Renamed from GenerateSecp256K1Key)
extern int C_GenerateSecp256K1Key(char* k, int kLen, char** privateKey, int* privateKeyLen, char** publicKey, int* publicKeyLen);

// C_GenerateBLS12381Key 导出版本 (Renamed from GenerateBLS12381Key)
extern int C_GenerateBLS12381Key(char* k, int kLen, char** privateKey, int* privateKeyLen, char** publicKey, int* publicKeyLen);

#ifdef __cplusplus
}
#endif
