# 节点信息
DEFAULT_NODE_ID = 0

# IP,这个好像没什么用
DEFAULT_NODE_IP = "127.0.0.1"

# GRPC
DEFAULT_GRPC_PORT = 1234

# LAYER 2 NODE
DEFAULT_LAYER2NODE_IP = "127.0.0.1"
DEFAULT_LAYER2NODE_PORT = 50051

# OTHER NODES
DEFAULT_OTHER_NODE_GRPC_ADDRESSES = {}
DEFAULT_ALL_NODE_NUM = 9

# PATH
DEFAULT_STORAGE_PATH = "meta"
DEFAULT_LOG_PATH = "logs"
DEFAULT_CERT_PATH = "certs"

# Process Worker并行数
DEFAULT_NUM_PROCESS_WORKER = 1

# 是否冗余
DEFAULT_REDUNDANCY = False

# EC
DEFAULT_RS_CODE_N = 9
DEFAULT_RS_CODE_K = 6

DEFAULT_IS_RECOVERY = True
