# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class RappaMasterStub(object):
    """**
    NOTE: 定义Master处的接口
    *
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommitSlot = channel.unary_unary(
                '/service.RappaMaster/CommitSlot',
                request_serializer=service__pb2.SlotCommitRequest.SerializeToString,
                response_deserializer=service__pb2.SlotCommitResponse.FromString,
                )


class RappaMasterServicer(object):
    """**
    NOTE: 定义Master处的接口
    *
    """

    def CommitSlot(self, request, context):
        """CommitSlot Executor向Master提交自己完成的Task Slot
        rpc CommitProof (ProofCommitRequest) returns (ProofCommitResponse); // TODO DataProver向Master提交自己完成的Proof
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RappaMasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommitSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSlot,
                    request_deserializer=service__pb2.SlotCommitRequest.FromString,
                    response_serializer=service__pb2.SlotCommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.RappaMaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RappaMaster(object):
    """**
    NOTE: 定义Master处的接口
    *
    """

    @staticmethod
    def CommitSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.RappaMaster/CommitSlot',
            service__pb2.SlotCommitRequest.SerializeToString,
            service__pb2.SlotCommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class RappaExecutorStub(object):
    """**
    NOTE: 定义Executor处的接口
    *
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/service.RappaExecutor/Heartbeat',
                request_serializer=service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=service__pb2.HeartbeatResponse.FromString,
                )
        self.Schedule = channel.unary_unary(
                '/service.RappaExecutor/Schedule',
                request_serializer=service__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=service__pb2.ScheduleResponse.FromString,
                )
        self.Collect = channel.unary_unary(
                '/service.RappaExecutor/Collect',
                request_serializer=service__pb2.RecoverRequest.SerializeToString,
                response_deserializer=service__pb2.RecoverResponse.FromString,
                )


class RappaExecutorServicer(object):
    """**
    NOTE: 定义Executor处的接口
    *
    """

    def Heartbeat(self, request, context):
        """Heartbeat 向follower同步slot状态，同时监控节点状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Schedule(self, request, context):
        """Schedule 用于向节点发送调度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Collect(self, request, context):
        """Collect 用于向节点收集chunk，恢复文件数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RappaExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=service__pb2.HeartbeatRequest.FromString,
                    response_serializer=service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Schedule,
                    request_deserializer=service__pb2.ScheduleRequest.FromString,
                    response_serializer=service__pb2.ScheduleResponse.SerializeToString,
            ),
            'Collect': grpc.unary_unary_rpc_method_handler(
                    servicer.Collect,
                    request_deserializer=service__pb2.RecoverRequest.FromString,
                    response_serializer=service__pb2.RecoverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.RappaExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RappaExecutor(object):
    """**
    NOTE: 定义Executor处的接口
    *
    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.RappaExecutor/Heartbeat',
            service__pb2.HeartbeatRequest.SerializeToString,
            service__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.RappaExecutor/Schedule',
            service__pb2.ScheduleRequest.SerializeToString,
            service__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Collect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.RappaExecutor/Collect',
            service__pb2.RecoverRequest.SerializeToString,
            service__pb2.RecoverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
