# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from network.Grpc.service import services_pb2 as services__pb2


class CoordinatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/coordinator.Coordinator/Heartbeat',
                request_serializer=services__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=services__pb2.HeartbeatResponse.FromString,
                )
        self.Schedule = channel.unary_unary(
                '/coordinator.Coordinator/Schedule',
                request_serializer=services__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=services__pb2.ScheduleResponse.FromString,
                )
        self.EpochVote = channel.unary_unary(
                '/coordinator.Coordinator/EpochVote',
                request_serializer=services__pb2.EpochVoteRequest.SerializeToString,
                response_deserializer=services__pb2.EpochVoteResponse.FromString,
                )
        self.CommitSlot = channel.unary_unary(
                '/coordinator.Coordinator/CommitSlot',
                request_serializer=services__pb2.SlotCommitRequest.SerializeToString,
                response_deserializer=services__pb2.SlotCommitResponse.FromString,
                )


class CoordinatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Heartbeat 向follower同步slot状态，同时监控节点状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Schedule(self, request, context):
        """Schedule 用于向节点发送调度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EpochVote(self, request, context):
        """EpochVote 投票epoch，用于上链
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitSlot(self, request, context):
        """Commit 节点向Coordinator返回自己已经完成的Task Slot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=services__pb2.HeartbeatRequest.FromString,
                    response_serializer=services__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Schedule,
                    request_deserializer=services__pb2.ScheduleRequest.FromString,
                    response_serializer=services__pb2.ScheduleResponse.SerializeToString,
            ),
            'EpochVote': grpc.unary_unary_rpc_method_handler(
                    servicer.EpochVote,
                    request_deserializer=services__pb2.EpochVoteRequest.FromString,
                    response_serializer=services__pb2.EpochVoteResponse.SerializeToString,
            ),
            'CommitSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSlot,
                    request_deserializer=services__pb2.SlotCommitRequest.FromString,
                    response_serializer=services__pb2.SlotCommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coordinator.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coordinator.Coordinator/Heartbeat',
            services__pb2.HeartbeatRequest.SerializeToString,
            services__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coordinator.Coordinator/Schedule',
            services__pb2.ScheduleRequest.SerializeToString,
            services__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EpochVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coordinator.Coordinator/EpochVote',
            services__pb2.EpochVoteRequest.SerializeToString,
            services__pb2.EpochVoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coordinator.Coordinator/CommitSlot',
            services__pb2.SlotCommitRequest.SerializeToString,
            services__pb2.SlotCommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
