# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import network.Grpc.service.service_pb2 as service__pb2


class CoordinatorStub(object):
    """这个是layer端的服务协议
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommitSlot = channel.unary_unary(
                '/service.Coordinator/CommitSlot',
                request_serializer=service__pb2.SlotCommitRequest.SerializeToString,
                response_deserializer=service__pb2.SlotCommitResponse.FromString,
                )


class CoordinatorServicer(object):
    """这个是layer端的服务协议
    """

    def CommitSlot(self, request, context):
        """Commit 节点向Coordinator返回自己已经完成的Task Slot
        TODO: 这里有一个提交proof的接口，先不实现
        rpc CommitProof (ProofCommitRequest) returns (ProofCommitRespnse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommitSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSlot,
                    request_deserializer=service__pb2.SlotCommitRequest.FromString,
                    response_serializer=service__pb2.SlotCommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """这个是layer端的服务协议
    """

    @staticmethod
    def CommitSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.Coordinator/CommitSlot',
            service__pb2.SlotCommitRequest.SerializeToString,
            service__pb2.SlotCommitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class NodeExecutorStub(object):
    """这个是节点端的服务协议
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/service.NodeExecutor/Heartbeat',
                request_serializer=service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=service__pb2.HeartbeatResponse.FromString,
                )
        self.Schedule = channel.unary_unary(
                '/service.NodeExecutor/Schedule',
                request_serializer=service__pb2.ScheduleRequest.SerializeToString,
                response_deserializer=service__pb2.ScheduleResponse.FromString,
                )


class NodeExecutorServicer(object):
    """这个是节点端的服务协议
    """

    def Heartbeat(self, request, context):
        """Heartbeat 向follower同步slot状态，同时监控节点状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Schedule(self, request, context):
        """Schedule 用于向节点发送调度
        投票包含在heartbeat里
        // EpochVote 投票epoch，用于上链
        rpc EpochVote (EpochVoteRequest) returns (EpochVoteResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=service__pb2.HeartbeatRequest.FromString,
                    response_serializer=service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Schedule,
                    request_deserializer=service__pb2.ScheduleRequest.FromString,
                    response_serializer=service__pb2.ScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.NodeExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeExecutor(object):
    """这个是节点端的服务协议
    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.NodeExecutor/Heartbeat',
            service__pb2.HeartbeatRequest.SerializeToString,
            service__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.NodeExecutor/Schedule',
            service__pb2.ScheduleRequest.SerializeToString,
            service__pb2.ScheduleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
